project_id = "ngzodolcmriqlcccpicz"

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.check-follow-ups]
verify_jwt = false

[functions.test-manychat]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.kiwify-auth]
verify_jwt = true

[functions.kiwify-setup-webhook]
verify_jwt = true

[functions.sync-manychat-leads]
verify_jwt = true

[functions.manychat-webhook]
verify_jwt = false

[functions.abandoned-cart-alert]
verify_jwt = true

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-message]
verify_jwt = true

[functions.zapi-ai-respond]
verify_jwt = false

[functions.process-training-document]
verify_jwt = true

[functions.zapi-setup-webhook]
verify_jwt = true

[functions.send-scheduled-messages]
verify_jwt = false

[functions.instagram-webhook]
verify_jwt = false

[functions.instagram-dm-webhook]
verify_jwt = false

[functions.facebook-webhook]
verify_jwt = false

[functions.meta-send-message]
verify_jwt = true

[functions.meta-ai-respond]
verify_jwt = true

[functions.weekly-report]
verify_jwt = false

[functions.manychat-send-message]
verify_jwt = true

[functions.manychat-find-subscriber]
verify_jwt = true

[functions.generate-chat-summary]
verify_jwt = true

[functions.generate-chat-transcription]
verify_jwt = true
