project_id = "ngzodolcmriqlcccpicz"

[functions.send-whatsapp-notification]
verify_jwt = true

[functions.check-follow-ups]
verify_jwt = false

[functions.test-manychat]
verify_jwt = false

[functions.kiwify-webhook]
verify_jwt = false

[functions.kiwify-auth]
verify_jwt = true

[functions.kiwify-setup-webhook]
verify_jwt = true

[functions.sync-manychat-leads]
verify_jwt = true